# Nom de l'application
spring:
  application:
    name: spring-gateway-example
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route 1 - Requ�te vers /predicate1/** redirig�e vers http://localhost:8080
                    - id: test         # identifiant unique de la route
                      uri: https://www.google.com # URI cible (donc ton url django)
                      predicates:                 # Conditions � remplir pour que cette route s'applique
                        - Path=/test/**     # Ici : l'URL doit commencer par /test/

                    # Route 2 - M�me logique que route 1
                    - id: predicate2_route
                      uri: http://localhost:8080
                      predicates:
                        - Path=/predicate2/**

                    # Route 3 - Redirige vers un service s�curis� avec filtre d'authentification JWT
                    - id: secured1_route
                      uri: http://localhost:8888/secured
                      predicates:
                        - Path=/predicate3/**
                      filters:
                        - name: AuthenticationFilter  # Applique le filtre perso pour authentifier les requ�tes

                    # Route 4 - M�me logique que route 3
                    - id: secured2_route
                      uri: http://localhost:8888/secured
                      predicates:
                        - Path=/predicate4/**
                      filters:
                        - name: AuthenticationFilter

                    # Route 5 - Accessible sans authentification (route "publique")
                    - id: authentication_route
                      uri: http://localhost:8988
                      predicates:
                        - Path=/authentication/**

jwt:
  secret: 63E7E8BE05A8C6EF206C75DF2D34F60FAA2C84E7F1B2095492A0056416056583
gateway:
  open:
    endpoints:
      - /authentication/client/register
      - /authentication/admin/register
      - /authentication/validate
      - /authentication/generate

server:
  port: 8888
